from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap
from front import FrontMainClass

class ProfileMainClass(object):
    def setupUi(self, profDialog):
        profDialog.setObjectName("profDialog")
        profDialog.resize(549, 589)
        self.presentProfileFrame = QtWidgets.QFrame(profDialog)
        self.presentProfileFrame.setGeometry(QtCore.QRect(-1, -1, 181, 591))
        self.presentProfileFrame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.presentProfileFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.presentProfileFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.presentProfileFrame.setObjectName("presentProfileFrame")

        self.profilepic = QtWidgets.QLabel(self.presentProfileFrame)
        self.profilepic.setGeometry(QtCore.QRect(6, 25, 171, 161))
        self.profilepic.setObjectName("profilepic")
        self.profpic = QPixmap("./img/prof.jpg")
        self.profilepic.setPixmap(self.profpic)

        self.recentFrame = QtWidgets.QFrame(self.presentProfileFrame)
        self.recentFrame.setGeometry(QtCore.QRect(3, 200, 176, 387))
        self.recentFrame.setStyleSheet("background-color: rgb(255, 250, 246);")
        self.recentFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.recentFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.recentFrame.setObjectName("recentFrame")

        self.recentEvents = QtWidgets.QLabel(self.recentFrame)
        self.recentEvents.setGeometry(QtCore.QRect(10, 11, 111, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setWeight(60)
        self.recentEvents.setFont(font)
        self.recentEvents.setObjectName("recentEvents")
        self.person1 = QtWidgets.QLabel(self.recentFrame)
        self.person1.setGeometry(QtCore.QRect(23, 46, 70, 18))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.person1.setFont(font)
        self.person1.setObjectName("person1")
        self.person2 = QtWidgets.QLabel(self.recentFrame)
        self.person2.setGeometry(QtCore.QRect(23, 74, 70, 18))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.person2.setFont(font)
        self.person2.setObjectName("person2")
        self.person3 = QtWidgets.QLabel(self.recentFrame)
        self.person3.setGeometry(QtCore.QRect(23, 102, 70, 18))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.person3.setFont(font)
        self.person3.setObjectName("person3")
        self.person4 = QtWidgets.QLabel(self.recentFrame)
        self.person4.setGeometry(QtCore.QRect(23, 131, 70, 18))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.person4.setFont(font)
        self.person4.setObjectName("person4")
        self.person5 = QtWidgets.QLabel(self.recentFrame)
        self.person5.setGeometry(QtCore.QRect(23, 160, 70, 18))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.person5.setFont(font)
        self.person5.setObjectName("person5")
        self.person6 = QtWidgets.QLabel(self.recentFrame)
        self.person6.setGeometry(QtCore.QRect(23, 188, 70, 18))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.person6.setFont(font)
        self.person6.setObjectName("person6")
        self.person7 = QtWidgets.QLabel(self.recentFrame)
        self.person7.setGeometry(QtCore.QRect(23, 216, 70, 18))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.person7.setFont(font)
        self.person7.setObjectName("person7")
        self.person8 = QtWidgets.QLabel(self.recentFrame)
        self.person8.setGeometry(QtCore.QRect(23, 243, 70, 18))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.person8.setFont(font)
        self.person8.setObjectName("person8")
        self.person9 = QtWidgets.QLabel(self.recentFrame)
        self.person9.setGeometry(QtCore.QRect(23, 271, 70, 18))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.person9.setFont(font)
        self.person9.setObjectName("person9")
        self.person10 = QtWidgets.QLabel(self.recentFrame)
        self.person10.setGeometry(QtCore.QRect(23, 296, 70, 18))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.person10.setFont(font)
        self.person10.setObjectName("person10")
        self.detailsFrame = QtWidgets.QFrame(profDialog)
        self.detailsFrame.setGeometry(QtCore.QRect(179, -1, 371, 201))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.detailsFrame.setFont(font)
        self.detailsFrame.setStyleSheet("background-color: rgb(255, 255, 246);")
        self.detailsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.detailsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.detailsFrame.setObjectName("detailsFrame")
        self.userIdShow = QtWidgets.QLabel(self.detailsFrame)
        self.userIdShow.setGeometry(QtCore.QRect(30, 26, 150, 25))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.userIdShow.setFont(font)
        self.userIdShow.setObjectName("userIdShow")
        self.nameShow = QtWidgets.QLabel(self.detailsFrame)
        self.nameShow.setGeometry(QtCore.QRect(30, 72, 200, 25))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.nameShow.setFont(font)
        self.nameShow.setObjectName("nameShow")
        self.desiShow = QtWidgets.QLabel(self.detailsFrame)
        self.desiShow.setGeometry(QtCore.QRect(30, 118, 200, 25))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.desiShow.setFont(font)
        self.desiShow.setObjectName("desiShow")
        self.emailShow = QtWidgets.QLabel(self.detailsFrame)
        self.emailShow.setGeometry(QtCore.QRect(30, 165, 250, 25))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(13)
        font.setWeight(62)
        self.emailShow.setFont(font)
        self.emailShow.setObjectName("emailShow")
        self.userId = QtWidgets.QLabel(self.detailsFrame)
        self.userId.setGeometry(QtCore.QRect(30, 11, 75, 18))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.userId.setFont(font)
        self.userId.setObjectName("userId")
        self.name = QtWidgets.QLabel(self.detailsFrame)
        self.name.setGeometry(QtCore.QRect(30, 57, 75, 18))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.name.setFont(font)
        self.name.setObjectName("name")
        self.designation = QtWidgets.QLabel(self.detailsFrame)
        self.designation.setGeometry(QtCore.QRect(30, 103, 75, 18))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.designation.setFont(font)
        self.designation.setObjectName("designation")
        self.email = QtWidgets.QLabel(self.detailsFrame)
        self.email.setGeometry(QtCore.QRect(30, 152, 75, 18))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.email.setFont(font)
        self.email.setObjectName("email")

        self.logoutButton = QtWidgets.QPushButton(self.detailsFrame)
        self.logoutButton.setGeometry(QtCore.QRect(316, 4, 50, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.logoutButton.setFont(font)
        self.logoutButton.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.logoutButton.setObjectName("logoutButton")

        self.friendsFrame = QtWidgets.QFrame(profDialog)
        self.friendsFrame.setGeometry(QtCore.QRect(182, 202, 364, 384))
        self.friendsFrame.setStyleSheet("background-color: rgb(235, 241, 250);")

        self.designationList1 = QtWidgets.QLabel(self.friendsFrame)
        self.designationList1.setGeometry(QtCore.QRect(30, 25, 200, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(68)
        self.designationList1.setFont(font)
        self.designationList1.setObjectName("designationList1")

        self.designationList2 = QtWidgets.QLabel(self.friendsFrame)
        self.designationList2.setGeometry(QtCore.QRect(30, 65, 200, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(68)
        self.designationList2.setFont(font)
        self.designationList2.setObjectName("designationList2")

        self.designationList3 = QtWidgets.QLabel(self.friendsFrame)
        self.designationList3.setGeometry(QtCore.QRect(30, 105, 200, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(68)
        self.designationList3.setFont(font)
        self.designationList3.setObjectName("designationList3")

        self.designationList4 = QtWidgets.QLabel(self.friendsFrame)
        self.designationList4.setGeometry(QtCore.QRect(30, 145, 200, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(68)
        self.designationList4.setFont(font)
        self.designationList4.setObjectName("designationList4")

        self.designationList5 = QtWidgets.QLabel(self.friendsFrame)
        self.designationList5.setGeometry(QtCore.QRect(30, 185, 200, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(68)
        self.designationList5.setFont(font)
        self.designationList5.setObjectName("designationList5")

        self.designationList6 = QtWidgets.QLabel(self.friendsFrame)
        self.designationList6.setGeometry(QtCore.QRect(30, 225, 200, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(68)
        self.designationList6.setFont(font)
        self.designationList6.setObjectName("designationList6")

        self.designationList7 = QtWidgets.QLabel(self.friendsFrame)
        self.designationList7.setGeometry(QtCore.QRect(30, 265, 200, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(68)
        self.designationList7.setFont(font)
        self.designationList7.setObjectName("designationList7")

        self.designationList8 = QtWidgets.QLabel(self.friendsFrame)
        self.designationList8.setGeometry(QtCore.QRect(30, 305, 200, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(68)
        self.designationList8.setFont(font)
        self.designationList8.setObjectName("designationList8")


        self.retranslateUi(profDialog)
        QtCore.QMetaObject.connectSlotsByName(profDialog)
        

    def retranslateUi(self, profDialog):
        _translate = QtCore.QCoreApplication.translate
        profDialog.setWindowTitle(_translate("profDialog", "My Profile"))
        self.recentEvents.setText(_translate("profDialog", "Recent Chats"))
        self.person1.setText(_translate("profDialog", "Person1"))
        self.person2.setText(_translate("profDialog", "Person2"))
        self.person3.setText(_translate("profDialog", "Person3"))
        self.person4.setText(_translate("profDialog", "Person4"))
        self.person5.setText(_translate("profDialog", "Person5"))
        self.person6.setText(_translate("profDialog", "Person6"))
        self.person7.setText(_translate("profDialog", "Person7"))
        self.person8.setText(_translate("profDialog", "Person8"))
        self.person9.setText(_translate("profDialog", "Person9"))
        self.person10.setText(_translate("profDialog", "Person10"))
        self.userIdShow.setText(_translate("profDialog", "3001"))
        self.nameShow.setText(_translate("profDialog", "My Name"))
        self.desiShow.setText(_translate("profDialog", "Web Developer"))
        self.emailShow.setText(_translate("profDialog", "myemail@test.com"))
        self.userId.setText(_translate("profDialog", "UserId :"))
        self.name.setText(_translate("profDialog", "Name :"))
        self.designation.setText(_translate("profDialog", "Designation :"))
        self.email.setText(_translate("profDialog", "Email :"))
        self.designationList1.setText(_translate("profDialog", ">  HR"))
        self.designationList2.setText(_translate("profDialog", ">  Technical Sales"))
        self.designationList3.setText(_translate("profDialog", ">  Web Developer"))
        self.designationList4.setText(_translate("profDialog", ">  Business Analyst"))
        self.designationList5.setText(_translate("profDialog", ">  Software Tester"))
        self.designationList6.setText(_translate("profDialog", ">  Technical Support"))
        self.designationList7.setText(_translate("profDialog", ">  Network Engineer"))
        self.designationList8.setText(_translate("profDialog", ">  Software Developer"))
        self.logoutButton.setText(_translate("profDialog", "Logout"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    profDialog = QtWidgets.QDialog()
    ui = ProfileMainClass()
    ui.setupUi(profDialog)
    profDialog.show()
    sys.exit(app.exec_())
