
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap


class RegisterMainClass(object):
    def setupUi(self, window_title):
        window_title.setObjectName("window_title")
        window_title.resize(500, 600)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        window_title.setPalette(palette)
        window_title.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);")
        self.userid_label = QtWidgets.QLabel(window_title)
        self.userid_label.setGeometry(QtCore.QRect(82, 173, 60, 13))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.userid_label.setFont(font)
        self.userid_label.setObjectName("userid_label")
        self.username_label = QtWidgets.QLabel(window_title)
        self.username_label.setGeometry(QtCore.QRect(83, 228, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.username_label.setFont(font)
        self.username_label.setObjectName("username_label")
        self.password_label = QtWidgets.QLabel(window_title)
        self.password_label.setGeometry(QtCore.QRect(83, 289, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.password_label.setFont(font)
        self.password_label.setObjectName("password_label")
        self.email_label = QtWidgets.QLabel(window_title)
        self.email_label.setGeometry(QtCore.QRect(84, 352, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.email_label.setFont(font)
        self.email_label.setObjectName("email_label")
        self.branch_label = QtWidgets.QLabel(window_title)
        self.branch_label.setGeometry(QtCore.QRect(83, 417, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.branch_label.setFont(font)
        self.branch_label.setObjectName("branch_label")
        self.gender_label = QtWidgets.QLabel(window_title)
        self.gender_label.setGeometry(QtCore.QRect(82, 482, 60, 13))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.gender_label.setFont(font)
        self.gender_label.setObjectName("gender_label")
        self.userid_entry = QtWidgets.QLineEdit(window_title)
        self.userid_entry.setGeometry(QtCore.QRect(225, 164, 190, 23))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.userid_entry.setFont(font)
        self.userid_entry.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.userid_entry.setMaxLength(15)
        self.userid_entry.setObjectName("userid_entry")
        self.username_entry = QtWidgets.QLineEdit(window_title)
        self.username_entry.setGeometry(QtCore.QRect(225, 222, 190, 23))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.username_entry.setFont(font)
        self.username_entry.setStyleSheet("background-color: rgb(240, 240, 240);\n"
"")
        self.username_entry.setMaxLength(50)
        self.username_entry.setObjectName("username_entry")
        self.password_entry = QtWidgets.QLineEdit(window_title)
        self.password_entry.setGeometry(QtCore.QRect(225, 282, 190, 23))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.password_entry.setFont(font)
        self.password_entry.setWhatsThis("")
        self.password_entry.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.password_entry.setMaxLength(20)
        self.password_entry.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.password_entry.setObjectName("password_entry")
        self.email_entry = QtWidgets.QLineEdit(window_title)
        self.email_entry.setGeometry(QtCore.QRect(226, 344, 190, 23))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.email_entry.setFont(font)
        self.email_entry.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.email_entry.setMaxLength(50)
        self.email_entry.setObjectName("email_entry")
        self.branch_entry = QtWidgets.QComboBox(window_title)
        self.branch_entry.setGeometry(QtCore.QRect(227, 413, 190, 23))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.branch_entry.setFont(font)
        self.branch_entry.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.branch_entry.setStyleSheet("background-color: rgb(240, 240, 240);\n"
"")
        self.branch_entry.setObjectName("branch_entry")
        self.branch_entry.addItem("")
        self.branch_entry.addItem("")
        self.branch_entry.addItem("")
        self.branch_entry.addItem("")
        self.branch_entry.addItem("")
        self.branch_entry.addItem("")
        self.branch_entry.addItem("")
        self.branch_entry.addItem("")
        self.branch_entry.addItem("")
        self.branch_entry.addItem("")
        self.gender_entry1 = QtWidgets.QRadioButton(window_title)
        self.gender_entry1.setGeometry(QtCore.QRect(236, 481, 51, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.gender_entry1.setFont(font)
        self.gender_entry1.setObjectName("gender_entry1")
        self.gender_entry2 = QtWidgets.QRadioButton(window_title)
        self.gender_entry2.setGeometry(QtCore.QRect(328, 481, 81, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.gender_entry2.setFont(font)
        self.gender_entry2.setObjectName("gender_entry2")
        self.pushButton = QtWidgets.QPushButton(window_title)
        self.pushButton.setGeometry(QtCore.QRect(178, 543, 115, 35))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 139, 26))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 139, 26))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 139, 26))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 139, 26))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 139, 26))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 139, 26))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 139, 26))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 139, 26))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 139, 26))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.pushButton.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("background-color: rgb(50, 139, 26);\n"
"color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(window_title)
        self.label.setGeometry(QtCore.QRect(104, 20, 281, 121))
        self.im1 = QPixmap("./img/reg.png")
        self.label.setPixmap(self.im1)
        #self.label.setStyleSheet("image: url(:/newPrefix/reg.png);")
        self.label.setText("")
        self.label.setObjectName("label")

        self.retranslateUi(window_title)
        QtCore.QMetaObject.connectSlotsByName(window_title)

    def retranslateUi(self, window_title):
        _translate = QtCore.QCoreApplication.translate
        window_title.setWindowTitle(_translate("window_title", "Registration Form"))
        self.userid_label.setText(_translate("window_title", "UserID"))
        self.username_label.setText(_translate("window_title", "Username"))
        self.password_label.setText(_translate("window_title", "Password"))
        self.email_label.setText(_translate("window_title", "Email"))
        self.branch_label.setText(_translate("window_title", "Designation"))
        self.gender_label.setText(_translate("window_title", "Gender"))
        self.branch_entry.setItemText(0, _translate("window_title", "Software Engineer"))
        self.branch_entry.setItemText(1, _translate("window_title", "HR"))
        self.branch_entry.setItemText(2, _translate("window_title", "Business Analyst"))
        self.branch_entry.setItemText(3, _translate("window_title", "Technical Support"))
        self.branch_entry.setItemText(4, _translate("window_title", "Software Tester"))
        self.branch_entry.setItemText(5, _translate("window_title", "Technical Sales"))
        self.branch_entry.setItemText(6, _translate("window_title", "Project Manager"))
        self.branch_entry.setItemText(7, _translate("window_title", "Web Developer"))
        self.branch_entry.setItemText(8, _translate("window_title", "Network Engineer"))
        self.branch_entry.setItemText(9, _translate("window_title", "Systems Analyst"))
        self.gender_entry1.setText(_translate("window_title", "Male"))
        self.gender_entry2.setText(_translate("window_title", "Female"))
        self.pushButton.setText(_translate("window_title", "Submit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    window_title = QtWidgets.QDialog()
    ui = RegisterMainClass()
    ui.setupUi(window_title)
    window_title.show()
    sys.exit(app.exec_())
